### ISSUE TITLE
Feature Request: Mix macro formatting

### ISSUE THREAD

**Issue by itsezc** [ForetagInc/palette#1]
### Preliminary checklist

- [X] I understand that all communication must be in English
- [X] I read the [Documentation](https://engineering.foret.ag)
- [X] I read the [Contributing guide](https://github.com/ForetagInc/.github/blob/master/CONTRIBUTING.md)
- [X] I agree to follow the [Code of Conduct](https://github.com/ForetagInc/.github/blob/master/CODE_OF_CONDUCT.md)
- [X] I searched the issues and discussions but couldn't find anything (or linked relevant results below)

### Problem

Currently the formatting is very verbose:

```rs
mix! {
	base: "bg:yellow",
	variants: {
		disabled: "bg:{} f:{} my:{}" => (
			tokens.color("yellow"),
			tokens.color("red"),
			tokens.spacing("8")
		),
		bold: "f:bold"
	},
}
```

The current implementation of the macro also doesn't cover the "base" field and also has no support for the "compounds" field.

### Solution

The implementation should look something similar to this:

```rs
mix! {
	base: "bg:yellow",
	variants: {
		disabled: "bg:{tokens.color(yellow)} f:{tokens.color(red)} my:{tokens.spacing(8)}",
		bold: "f:bold"
	},
	compounds: [
		[{ label: "example", bold: true }, "bg:{tokens.color("red")}"],
	]
}
```

### Alternatives

N/A

### Contribution

No, I cannot contribute further

### Keywords

mix, macro, formatting, variants, compounds

**Comment by KennethGomez** [comment]
I'll take a look on this

**Comment by itsezc** [comment]
Since we would be implementing the variants as part of the macro, maybe we can take this opportunity to pass types from `&P` into variants (and compounds) to ensure that the fields are fully type compatible. We have to keep in mind that `&P` is relative to the Props of a Yew component, which is dynamic.

**Comment by itsezc** [comment]
Also worth mentioning that `&P` can have many types of properties, but we want to primarily extract `bool` and `String` for variants to compare values with; additionally, for compounds, integer based types such as ints & floats maybe necessary - although these would be edge cases.

**Comment by KennethGomez** [comment]
For the formatting doing this syntax is really difficult macro-wise

```
disabled: "bg:{tokens.color(yellow)} f:{tokens.color(red)} my:{tokens.spacing(8)}",
```

I propose an alternative for this, approve it and I'll go forward with the implementation

```
disabled: ("bg:{} f:{} my:{}", tokens.color("yellow"), tokens.color("red"), tokens.spacing(8)),
```

**Comment by KennethGomez** [comment]
After discussing the conclusion that's been reached is this new format:
```rust
mix! {
	base: "bg:yellow",
	variants: {
		disabled: format!(
			"bg:{} f:{} my:{}",
			tokens.color("yellow"),
			tokens.color("red"),
			tokens.spacing(8)
		),
		bold: "f:bold"
	},
	compounds: [
		[
			{ label: "example", bold: true },
			format!(
				"bg:{}",
				tokens.color("red")
			)
		],
	]
}
 ```

**Comment by KennethGomez** [comment]
A new addition to the current syntax has to be done in order for type checking to work. The props variable identifier has to be included on the macro as following:
```rust
mix! { props => 
   ...
}
```
